//TODO: figure out a good way to handle actions from cards
//maybe an action list in each recipe object that can pass to a helper function
export const rareRecipes = [
  {
    name: "Spring Roll",
    pictureName: "springRoll",
    points: 2,
    status: "basicPlant",
    cost: {
      redTriangle: 1,
      greenCircle: 3,
    },
    energy: 1,
    description:
      "Place 2 ingredients from your hand onto your board. Refresh. All other players draw +1 card",
    actions: ["energy1", "placeIngredients2", "otherPlayersDraw"],
  },
];

export const basicRecipes = [
  {
    name: "Healthy Snack",
    pictureName: "healthySnack",
    points: 1,
    status: "basicPlant",
    cost: {
      greenCircle: 2,
    },
    energy: 1,
    description: "All other players draw +1 card",
    actions: ["otherPlayersDraw"],
  },
];

export const ingredients = [
  {
    name: "Bean Burger",
    pictureName: "beanBurger",
    value: {
      burger: 1,
      plant: 1,
      colorless: 0,
      spicy: 0,
      noodle: 0,
      sauce: 0,
      taco: 0,
      egg: 0,
      sweet: 0,
    },
  },
  {
    name: "Pepper",
    pictureName: "pepper",
    value: {
      burger: 0,
      plant: 1,
      colorless: 0,
      spicy: 1,
      noodle: 0,
      sauce: 0,
      taco: 0,
      egg: 0,
      sweet: 0,
    },
  },
  {
    name: "Pesto",
    pictureName: "pesto",
    value: {
      burger: 0,
      plant: 1,
      colorless: 0,
      spicy: 0,
      noodle: 0,
      sauce: 1,
      taco: 0,
      egg: 0,
      sweet: 0,
    },
  },
  {
    name: "Zoodles",
    pictureName: "zoodles",
    value: {
      burger: 0,
      plant: 1,
      colorless: 0,
      spicy: 0,
      noodle: 1,
      sauce: 0,
      taco: 0,
      egg: 0,
      sweet: 0,
    },
  },
  {
    name: "Nopales Taco",
    pictureName: "nopalesTaco",
    value: {
      burger: 0,
      plant: 1,
      colorless: 0,
      spicy: 0,
      noodle: 0,
      sauce: 0,
      taco: 1,
      egg: 0,
      sweet: 0,
    },
  },
  {
    name: "Spaghetti",
    pictureName: "spaghetti",
    value: {
      burger: 0,
      plant: 0,
      colorless: 0,
      spicy: 0,
      noodle: 2,
      sauce: 0,
      taco: 0,
      egg: 0,
      sweet: 0,
    },
  },
  {
    name: "Ketchup",
    pictureName: "ketchup",
    value: {
      burger: 0,
      plant: 0,
      colorless: 0,
      spicy: 0,
      noodle: 0,
      sauce: 2,
      taco: 0,
      egg: 0,
      sweet: 0,
    },
  },
  {
    name: "Tsuyu",
    pictureName: "tsuyu",
    value: {
      burger: 0,
      plant: 0,
      colorless: 0,
      spicy: 0,
      noodle: 1,
      sauce: 1,
      taco: 0,
      egg: 0,
      sweet: 0,
    },
  },
  {
    name: "Hot Sauce",
    pictureName: "hotSauce",
    value: {
      burger: 0,
      plant: 0,
      colorless: 0,
      spicy: 1,
      noodle: 0,
      sauce: 1,
      taco: 0,
      egg: 0,
      sweet: 0,
    },
  },
  {
    name: "Ghost Taco",
    pictureName: "ghostTaco",
    value: {
      burger: 0,
      plant: 0,
      colorless: 0,
      spicy: 1,
      noodle: 0,
      sauce: 0,
      taco: 1,
      egg: 0,
      sweet: 0,
    },
  },
  {
    name: "Guacamole",
    pictureName: "guacamole",
    value: {
      burger: 0,
      plant: 0,
      colorless: 0,
      spicy: 0,
      noodle: 0,
      sauce: 1,
      taco: 1,
      egg: 0,
      sweet: 0,
    },
  },
  {
    name: "Carrot",
    pictureName: "carrot",
    value: {
      burger: 0,
      plant: 1,
      colorless: 0,
      spicy: 0,
      noodle: 0,
      sauce: 0,
      taco: 0,
      egg: 0,
      sweet: 0,
    },
  },
  {
    name: "Burger",
    pictureName: "burger",
    value: {
      burger: 1,
      plant: 0,
      colorless: 0,
      spicy: 0,
      noodle: 0,
      sauce: 0,
      taco: 0,
      egg: 0,
      sweet: 0,
    },
  },
  {
    name: "Taco",
    pictureName: "taco",
    value: {
      burger: 0,
      plant: 0,
      colorless: 0,
      spicy: 0,
      noodle: 0,
      sauce: 0,
      taco: 1,
      egg: 0,
      sweet: 0,
    },
  },
  {
    name: "Ice Cream",
    pictureName: "iceCream",
    value: {
      burger: 0,
      plant: 0,
      colorless: 0,
      spicy: 0,
      noodle: 0,
      sauce: 0,
      taco: 0,
      egg: 0,
      sweet: 1,
    },
  },
  {
    name: "Mochi Donut",
    pictureName: "mochiDonut",
    value: {
      burger: 0,
      plant: 0,
      colorless: 0,
      spicy: 0,
      noodle: 0,
      sauce: 0,
      taco: 0,
      egg: 0,
      sweet: 1,
    },
  },
  {
    name: "Fruit Snacks",
    pictureName: "fruitSnacks",
    value: {
      burger: 0,
      plant: 0,
      colorless: 0,
      spicy: 0,
      noodle: 0,
      sauce: 0,
      taco: 0,
      egg: 0,
      sweet: 1,
    },
  },
  {
    name: "Egg",
    pictureName: "egg",
    value: {
      burger: 0,
      plant: 0,
      colorless: 0,
      spicy: 0,
      noodle: 0,
      sauce: 0,
      taco: 0,
      egg: 1,
      sweet: 0,
    },
  },
];
export const playerRoles = [
  {
    name: "Sasha",
    actions: [],
  },
  {
    name: "Coco",
    actions: [],
  },
  {
    name: "Damien",
    actions: [],
  },
  {
    name: "Fronk",
    actions: [],
  },
  {
    name: "Shinra",
    actions: [],
  },
  {
    name: "Ramona",
    actions: [],
  },
];
