export default {
  beanBurger: {
    name: "Bean Burger",
    value: {
      ingredientBurger: 1,
      ingredientPlant: 1,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 0,
      ingredientSauce: 0,
      ingredientTaco: 0,
      ingredientEgg: 0,
      ingredientSweet: 0,
    },
  },
  pepper: {
    name: "Pepper",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 1,
      ingredientColorless: 0,
      ingredientSpicy: 1,
      ingredientNoodle: 0,
      ingredientSauce: 0,
      ingredientTaco: 0,
      ingredientEgg: 0,
      ingredientSweet: 0,
    },
  },
  pesto: {
    name: "Pesto",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 1,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 0,
      ingredientSauce: 1,
      ingredientTaco: 0,
      ingredientEgg: 0,
      ingredientSweet: 0,
    },
  },
  zoodles: {
    name: "Zoodles",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 1,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 1,
      ingredientSauce: 0,
      ingredientTaco: 0,
      ingredientEgg: 0,
      ingredientSweet: 0,
    },
  },
  nopalesTaco: {
    name: "Nopales Taco",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 1,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 0,
      ingredientSauce: 0,
      ingredientTaco: 1,
      ingredientEgg: 0,
      ingredientSweet: 0,
    },
  },
  spaghetti: {
    name: "Spaghetti",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 0,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 2,
      ingredientSauce: 0,
      ingredientTaco: 0,
      ingredientEgg: 0,
      ingredientSweet: 0,
    },
  },
  ketchup: {
    name: "Ketchup",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 0,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 0,
      ingredientSauce: 2,
      ingredientTaco: 0,
      ingredientEgg: 0,
      ingredientSweet: 0,
    },
  },
  tsuyu: {
    name: "Tsuyu",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 0,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 1,
      ingredientSauce: 1,
      ingredientTaco: 0,
      ingredientEgg: 0,
      ingredientSweet: 0,
    },
  },
  hotSauce: {
    name: "Hot Sauce",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 0,
      ingredientColorless: 0,
      ingredientSpicy: 1,
      ingredientNoodle: 0,
      ingredientSauce: 1,
      ingredientTaco: 0,
      ingredientEgg: 0,
      ingredientSweet: 0,
    },
  },
  ghostTaco: {
    name: "Ghost Taco",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 0,
      ingredientColorless: 0,
      ingredientSpicy: 1,
      ingredientNoodle: 0,
      ingredientSauce: 0,
      ingredientTaco: 1,
      ingredientEgg: 0,
      ingredientSweet: 0,
    },
  },
  guacamole: {
    name: "Guacamole",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 0,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 0,
      ingredientSauce: 1,
      ingredientTaco: 1,
      ingredientEgg: 0,
      ingredientSweet: 0,
    },
  },
  carrot: {
    name: "Carrot",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 1,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 0,
      ingredientSauce: 0,
      ingredientTaco: 0,
      ingredientEgg: 0,
      ingredientSweet: 0,
    },
  },
  burger: {
    name: "Burger",
    value: {
      ingredientBurger: 1,
      ingredientPlant: 0,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 0,
      ingredientSauce: 0,
      ingredientTaco: 0,
      ingredientEgg: 0,
      ingredientSweet: 0,
    },
  },
  taco: {
    name: "Taco",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 0,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 0,
      ingredientSauce: 0,
      ingredientTaco: 1,
      ingredientEgg: 0,
      ingredientSweet: 0,
    },
  },
  iceCream: {
    name: "Ice Cream",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 0,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 0,
      ingredientSauce: 0,
      ingredientTaco: 0,
      ingredientEgg: 0,
      ingredientSweet: 1,
    },
  },
  mochiDonut: {
    name: "Mochi Donut",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 0,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 0,
      ingredientSauce: 0,
      ingredientTaco: 0,
      ingredientEgg: 0,
      ingredientSweet: 1,
    },
  },
  fruitSnacks: {
    name: "Fruit Snacks",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 0,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 0,
      ingredientSauce: 0,
      ingredientTaco: 0,
      ingredientEgg: 0,
      ingredientSweet: 1,
    },
  },
  egg: {
    name: "Egg",
    value: {
      ingredientBurger: 0,
      ingredientPlant: 0,
      ingredientColorless: 0,
      ingredientSpicy: 0,
      ingredientNoodle: 0,
      ingredientSauce: 0,
      ingredientTaco: 0,
      ingredientEgg: 1,
      ingredientSweet: 0,
    },
  },
};
